"""Protocol interfaces for MessageBus, ToolRegistry, SkillRegistry, MemoryStore."""

from __future__ import annotations

from typing import Any, Callable, Protocol, runtime_checkable

from agentforge.types.message import Message


@runtime_checkable
class MessageBus(Protocol):
    """Protocol for async publish/subscribe message bus implementations."""
    async def subscribe(self, topic: str, handler: Callable[[Message], Any]) -> str: ...
    async def unsubscribe(self, subscription_id: str) -> None: ...
    async def publish(self, topic: str, message: Message) -> None: ...
    async def request(self, topic: str, message: Message, timeout: float = 5.0) -> Message: ...


@runtime_checkable
class ToolRegistry(Protocol):
    """Protocol for tool registration and lookup."""
    def register(self, name: str, handler: Callable, schema: dict[str, Any]) -> None: ...
    def unregister(self, name: str) -> None: ...
    def get(self, name: str) -> tuple[Callable, dict[str, Any]] | None: ...
    def list_tools(self) -> list[str]: ...


@runtime_checkable
class SkillRegistry(Protocol):
    """Protocol for skill registration and discovery."""
    def register(self, name: str, handler: Callable, deps: list[str] | None = None) -> None: ...
    def get(self, name: str) -> Callable | None: ...
    def discover(self, tag: str | None = None) -> list[str]: ...


@runtime_checkable
class MemoryStore(Protocol):
    """Protocol for async key-value memory storage."""
    async def store(self, key: str, value: Any) -> None: ...
    async def retrieve(self, key: str) -> Any | None: ...
    async def delete(self, key: str) -> None: ...
